Issue 6 utils loaders
eutampieri/OOP20-procedural-dungeon pull request #13
Opened 2021-03-22 09:33 UTC by Roccubalbetta

2021-03-22 11:07 UTC, jackmounts requested changes
ma non cè parte dei commit che ci sono nell'altra pull?

2021-03-22 11:10 UTC, jackmounts commented
i commit sono anche nella pull della issue #14

2021-03-22 12:56 UTC, eutampieri commented
SI ma non dovrebbe essere un problema

2021-03-23 10:31 UTC, jackmounts approved these changes

2021-03-25 14:20 UTC, eutampieri requested changes

2021-03-25 14:20 UTC, eutampieri commented on src/eu/eutampieri/catacombs/ui/utils/TextLoader.java
> +	public static String loadText(String path) {
Please don't pass paths as Strings

2021-03-29 11:56 UTC, eutampieri requested changes

2021-03-29 11:56 UTC, eutampieri commented on src/main/java/eu/eutampieri/catacombs/ui/utils/ImageLoader.java
> +		BufferedImage image = null;
Make it `final` and don't assign a null pointer

2021-03-29 11:56 UTC, eutampieri commented on src/main/java/eu/eutampieri/catacombs/ui/utils/ImageLoader.java
> +			e.printStackTrace();
Rethrow the exception instead of returning a null pointer

2021-03-29 11:56 UTC, eutampieri commented on src/main/java/eu/eutampieri/catacombs/ui/utils/TextLoader.java
> +			game.stop();
Same here, don’t stop game but rethrow the exception

2021-03-29 11:57 UTC, eutampieri requested changes

2021-03-29 11:57 UTC, eutampieri commented on src/main/java/eu/eutampieri/catacombs/ui/utils/TextLoader.java
> +		try (Scanner scan = new Scanner(TextLoader.class.getResourceAsStream(path), "utf-8")){
It is better to replace "utf-8" with new Charset("UTF-8")

2021-03-29 13:16 UTC, eutampieri approved these changes

2021-03-29 13:45 UTC, eutampieri requested changes

2021-03-29 13:45 UTC, eutampieri commented on src/main/java/eu/eutampieri/catacombs/ui/utils/TextLoader.java
> +			final String file = "";
A useless variable?

2021-03-29 13:48 UTC, eutampieri approved these changes

2021-03-29 13:49 UTC, eutampieri commented
Let’s wait for the checks

2021-03-29 13:50 UTC, merged